### ISSUE TITLE
Issue with header file not found

### ISSUE THREAD

**Issue by dolbex** [Donky-Network/DonkySDK-iOS-Modular#7]
For some reason I'm now getting:

`/modules/Messaging/Rich/UI/Inbox/Helpers/Rich Cell/DRITableViewCell.h:12:9: 'DRUITheme.h' file not found`

**Comment by dolbex** [comment]
Strike that - apologies - I didn't update the files in xcode properly

**Comment by ben-moore** [comment]
Ok glad you found the issue - let us know if you have any further problems.

**Comment by dolbex** [comment]
Thanks @ben-moore - I am having an additional issue I could use a hand with.

**Comment by ben-moore** [comment]
@dolbex sure, feel free to open another issue on here or email sdk@mobiledonky.com
