### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by bombez** [Donky-Network/DonkySDK-iOS-Modular#9]
Hi,
We are currently using you library on a commercial app, and we are having problems with the version suggested on the site. We found out the issue disappear using the last version on this repository. When will we have this version on cocapods?
Thanks.

**Comment by ben-moore** [comment]
Hi @bombez, can you describe a little more what issue you are having?  Cocoapods should be up to date, although we have another release due next week which will be released to both github and cocoapods.

**Comment by ben-moore** [comment]
Cocoapods were updated again last week with release https://github.com/Donky-Network/DonkySDK-iOS-Modular/tree/v4.8.2.0.  Closing this issue, please feel free to contact us again if you have any further problems.
